ARG version
FROM almalinux:${version:-9}
ARG  COURSE="DEVOPS"\
     DURATION="120HRS"\
     COMAPANY="JOINDEVOPS"
RUN echo "COURSE:$COURSE, DURATION:$DURATION"
ENV duration=$DURATION   
CMD ["sleep","100"]  